  
const arts = [
  {
    id: 1,
    size: '18" x 24"',
    medium: "oil paint",
    story: "Practicing An Art, No Matter How Well Or Badly, Is A Way To Make Your Soul Grow, For Heaven’s Sake. Sing In The Shower, Dance To The Radio, Tell Stories. Write A Poem To A Friend, Even A Lousy Poem. Do It As Well As You Possibly Can. You Will Get An Enormous Reward. You Will Have Created Something.",
    name: 'Gateaway',
    imageUrl: '/images/2.jpg',
    creator: 'Bruce Wayne',
    price: 250000,
    type: 'Pen Sketch',
    passion: 'ART',
    profession: 'Ceo| Wayne Enterprise'
  },
  {
    id: 2,
    size: '18" x 24"',
    medium: "oil paint",
    story: "Practicing An Art, No Matter How Well Or Badly, Is A Way To Make Your Soul Grow, For Heaven’s Sake. Sing In The Shower, Dance To The Radio, Tell Stories. Write A Poem To A Friend, Even A Lousy Poem. Do It As Well As You Possibly Can. You Will Get An Enormous Reward. You Will Have Created Something.", 
    name: "Old Man's thought",
    imageUrl: '/images/1.jpg',
    creator: 'Alfred Pennyworth',
    price: 5000,
    type: 'Sketch',
    passion: 'ART',
    profession: 'Ceo| Wayne Enterprise'
  },
  {
    id: 3,
    size: '18" x 24"',
    medium: "oil paint",
    story: "Practicing An Art, No Matter How Well Or Badly, Is A Way To Make Your Soul Grow, For Heaven’s Sake. Sing In The Shower, Dance To The Radio, Tell Stories. Write A Poem To A Friend, Even A Lousy Poem. Do It As Well As You Possibly Can. You Will Get An Enormous Reward. You Will Have Created Something.",
    name: 'Into the wild',
    imageUrl: '/images/3.jpg',
    creator: 'Oliver Queen',
    price: 65000,
    type: 'Canvas',
    passion: 'ART',
    profession: "Ceo| Queen's consoladaion"
 
  },
  {
    id: 4,
    size: '18" x 24"',
    medium: "oil paint",
    story: "Practicing An Art, No Matter How Well Or Badly, Is A Way To Make Your Soul Grow, For Heaven’s Sake. Sing In The Shower, Dance To The Radio, Tell Stories. Write A Poem To A Friend, Even A Lousy Poem. Do It As Well As You Possibly Can. You Will Get An Enormous Reward. You Will Have Created Something.",
    name: 'Raven',
    imageUrl: '/images/4.jpg',
    creator: 'Auther Curry',
    price: 77000,
    type: 'Digital Sketch',
    passion: 'ART',
    profession: 'Professional Diver'
  },
  {
    id: 5,
    size: '18" x 24"',
    medium: "oil paint",
    story: "Practicing An Art, No Matter How Well Or Badly, Is A Way To Make Your Soul Grow, For Heaven’s Sake. Sing In The Shower, Dance To The Radio, Tell Stories. Write A Poem To A Friend, Even A Lousy Poem. Do It As Well As You Possibly Can. You Will Get An Enormous Reward. You Will Have Created Something.",
    name: 'The Hidden Wonderland',
    imageUrl: '/images/5.jpg',
    creator: 'Diana Prince',
    price: 50000,
    type: 'Sketch',
    passion: 'ART',
    profession: 'Archeologist'
  },
  {
    id: 6,
    size: '18" x 24"',
    medium: "oil paint",
    story: "Practicing An Art, No Matter How Well Or Badly, Is A Way To Make Your Soul Grow, For Heaven’s Sake. Sing In The Shower, Dance To The Radio, Tell Stories. Write A Poem To A Friend, Even A Lousy Poem. Do It As Well As You Possibly Can. You Will Get An Enormous Reward. You Will Have Created Something.",
    name: 'Mandala',
    imageUrl: '/images/6.jpg',
    creator: 'Demian Wayne',
    price: 40000,
    type: 'Mandana',
    passion: 'ART',
    profession: 'Tech Geek'
  },
  {
    id: 7,
    size: '18" x 24"',
    medium: "oil paint",
    story: "Practicing An Art, No Matter How Well Or Badly, Is A Way To Make Your Soul Grow, For Heaven’s Sake. Sing In The Shower, Dance To The Radio, Tell Stories. Write A Poem To A Friend, Even A Lousy Poem. Do It As Well As You Possibly Can. You Will Get An Enormous Reward. You Will Have Created Something.",
    name: 'Blue and Black',
    imageUrl: '/images/7.jpg',
    creator: 'Jason Tod',
    price: 5000,
    type: 'Sketch',
    passion: 'ART',
    profession: 'Tech Geek'
  },
  {
    id: 8,
    size: '18" x 24"',
    medium: "oil paint",
    story: "Practicing An Art, No Matter How Well Or Badly, Is A Way To Make Your Soul Grow, For Heaven’s Sake. Sing In The Shower, Dance To The Radio, Tell Stories. Write A Poem To A Friend, Even A Lousy Poem. Do It As Well As You Possibly Can. You Will Get An Enormous Reward. You Will Have Created Something.",
    name: 'The Wildfire',
    imageUrl: '/images/9.jpg',
    creator: 'Dick Greyson',
    price: 65000,
    type: 'Sketch',
    passion: 'ART',
    profession: 'Fighter'
  },
  {
    id: 9,
    size: '18" x 24"',
    medium: "oil paint",
    story: "Practicing An Art, No Matter How Well Or Badly, Is A Way To Make Your Soul Grow, For Heaven’s Sake. Sing In The Shower, Dance To The Radio, Tell Stories. Write A Poem To A Friend, Even A Lousy Poem. Do It As Well As You Possibly Can. You Will Get An Enormous Reward. You Will Have Created Something.",
    name: 'Her Story',
    imageUrl: '/images/8.jpg',
    creator: 'Barbara Gordon',
    price: 77000,
    type: 'Sketch',
    passion: 'ART',
    profession: 'GCPD'
  },
  {
    id: 10,
    size: '18" x 24"',
    medium: "oil paint",
    story: "Practicing An Art, No Matter How Well Or Badly, Is A Way To Make Your Soul Grow, For Heaven’s Sake. Sing In The Shower, Dance To The Radio, Tell Stories. Write A Poem To A Friend, Even A Lousy Poem. Do It As Well As You Possibly Can. You Will Get An Enormous Reward. You Will Have Created Something.",
    name: 'The Good Cop',
    imageUrl: '/images/1.jpg',
    creator: 'James Gordon',
    price: 50000,
    type: 'Sketch',
    passion: 'ART',
    profession: 'Cop'
  },
 {
    id: 11,
    size: '18" x 24"',
    medium: "oil paint",
    story: "Practicing An Art, No Matter How Well Or Badly, Is A Way To Make Your Soul Grow, For Heaven’s Sake. Sing In The Shower, Dance To The Radio, Tell Stories. Write A Poem To A Friend, Even A Lousy Poem. Do It As Well As You Possibly Can. You Will Get An Enormous Reward. You Will Have Created Something.",
    name: 'The Society Within',
    imageUrl: '/images/2.jpg',
    creator: 'Aurther Fleck',
    price: 50000,
    type: 'Sketch',
    passion: 'ART',
    profession: 'Joker'
  },
  {
    id: 12,
    size: '18" x 24"',
    medium: "oil paint",
    story: "Practicing An Art, No Matter How Well Or Badly, Is A Way To Make Your Soul Grow, For Heaven’s Sake. Sing In The Shower, Dance To The Radio, Tell Stories. Write A Poem To A Friend, Even A Lousy Poem. Do It As Well As You Possibly Can. You Will Get An Enormous Reward. You Will Have Created Something.",
    name: 'Thoughts',
    imageUrl: '/images/3.jpg',
    creator: 'Raven',
    price: 40000,
    type: 'Sketch',
    passion: 'ART',
    profession: 'Student'
  },
  {
    id: 13,
    size: '18" x 24"',
    medium: "oil paint",
    story: "Practicing An Art, No Matter How Well Or Badly, Is A Way To Make Your Soul Grow, For Heaven’s Sake. Sing In The Shower, Dance To The Radio, Tell Stories. Write A Poem To A Friend, Even A Lousy Poem. Do It As Well As You Possibly Can. You Will Get An Enormous Reward. You Will Have Created Something.",
    name: 'Thunder',
    imageUrl: '/images/4.jpg',
    creator: 'Billy Batson',
    price: 5000,
    type: 'Sketch',
    passion: 'ART',
    profession: 'Student'
  },
  {
    id: 14,
    size: '18" x 24"',
    medium: "oil paint",
    story: "Practicing An Art, No Matter How Well Or Badly, Is A Way To Make Your Soul Grow, For Heaven’s Sake. Sing In The Shower, Dance To The Radio, Tell Stories. Write A Poem To A Friend, Even A Lousy Poem. Do It As Well As You Possibly Can. You Will Get An Enormous Reward. You Will Have Created Something.",
    name: 'Runner',
    imageUrl: '/images/5.jpg',
    creator: 'Barry Allen',
    price: 8500,
    type: 'Sketch',
    passion: 'ART',
    profession: 'Foreignsic Deparment'
  },
  {
    id: 15,
    size: '18" x 24"',
    medium: "oil paint",
    story: "Practicing An Art, No Matter How Well Or Badly, Is A Way To Make Your Soul Grow, For Heaven’s Sake. Sing In The Shower, Dance To The Radio, Tell Stories. Write A Poem To A Friend, Even A Lousy Poem. Do It As Well As You Possibly Can. You Will Get An Enormous Reward. You Will Have Created Something.",
    name: 'Stretchy',
    imageUrl: '/images/6.jpg',
    creator: 'Ralphy',
    price: 1500,
    type: 'Sketch',
    passion: 'ART',
    profession: 'PI'
  },
  {
    id: 7,
    size: '18" x 24"',
    medium: "oil paint",
    story: "Practicing An Art, No Matter How Well Or Badly, Is A Way To Make Your Soul Grow, For Heaven’s Sake. Sing In The Shower, Dance To The Radio, Tell Stories. Write A Poem To A Friend, Even A Lousy Poem. Do It As Well As You Possibly Can. You Will Get An Enormous Reward. You Will Have Created Something.",
    name: 'Blue and Black',
    imageUrl: '/images/7.jpg',
    creator: 'Jason Tod',
    price: 5000,
    type: 'Sketch',
    passion: 'ART',
    profession: 'Tech Geek'
  },
  {
    id: 1,
    name: 'Gateaway',
    imageUrl: '/images/2.jpg',
    creator: 'Bruce Wayne',
    price: 250000,
    type: 'Pen Sketch',
    passion: 'ART',
    profession: 'Ceo| Wayne Enterprise'
  },
  {
    id: 2,
    name: "Old Man's thought",
    imageUrl: '/images/1.jpg',
    creator: 'Alfred Pennyworth',
    price: 5000,
    type: 'Sketch',
    passion: 'ART',
    profession: 'Ceo| Wayne Enterprise'
  },
  {
    id: 3,
    name: 'Into the wild',
    imageUrl: '/images/3.jpg',
    creator: 'Oliver Queen',
    price: 65000,
    type: 'Canvas',
    passion: 'ART',
    profession: "Ceo| Queen's consoladaion"
 
  },
  {
    id: 4,
    name: 'Raven',
    imageUrl: '/images/4.jpg',
    creator: 'Auther Curry',
    price: 77000,
    type: 'Digital Sketch',
    passion: 'ART',
    profession: 'Professional Diver'
  },
  {
    id: 5,
    name: 'The Hidden Wonderland',
    imageUrl: '/images/5.jpg',
    creator: 'Diana Prince',
    price: 50000,
    type: 'Sketch',
    passion: 'ART',
    profession: 'Archeologist'
  },
  {
    id: 6,
    name: 'Mandala',
    imageUrl: '/images/6.jpg',
    creator: 'Demian Wayne',
    price: 40000,
    type: 'Mandana',
    passion: 'ART',
    profession: 'Tech Geek'
  },
  {
    id: 7,
    name: 'Blue and Black',
    imageUrl: '/images/7.jpg',
    creator: 'Jason Tod',
    price: 5000,
    type: 'Sketch',
    passion: 'ART',
    profession: 'Tech Geek'
  },
  {
    id: 8,
    name: 'The Wildfire',
    imageUrl: '/images/9.jpg',
    creator: 'Dick Greyson',
    price: 65000,
    type: 'Sketch',
    passion: 'ART',
    profession: 'Fighter'
  },
  {
    id: 9,
    name: 'Her Story',
    imageUrl: '/images/8.jpg',
    creator: 'Barbara Gordon',
    price: 77000,
    type: 'Sketch',
    passion: 'ART',
    profession: 'GCPD'
  },
  {
    id: 10,
    name: 'The Good Cop',
    imageUrl: '/images/1.jpg',
    creator: 'James Gordon',
    price: 50000,
    type: 'Sketch',
    passion: 'ART',
    profession: 'Cop'
  },
 {
    id: 11,
    name: 'The Society Within',
    imageUrl: '/images/2.jpg',
    creator: 'Aurther Fleck',
    price: 50000,
    type: 'Sketch',
    passion: 'ART',
    profession: 'Joker'
  },
  {
    id: 12,
    name: 'Thoughts',
    imageUrl: '/images/3.jpg',
    creator: 'Raven',
    price: 40000,
    type: 'Sketch',
    passion: 'ART',
    profession: 'Student'
  },
  {
    id: 13,
    name: 'Thunder',
    imageUrl: '/images/4.jpg',
    creator: 'Billy Batson',
    price: 5000,
    type: 'Sketch',
    passion: 'ART',
    profession: 'Student'
  },
  {
    id: 14,
    name: 'Runner',
    imageUrl: '/images/5.jpg',
    creator: 'Barry Allen',
    price: 8500,
    type: 'Sketch',
    passion: 'ART',
    profession: 'Foreignsic Deparment'
  },
  {
    id: 15,
    name: 'Stretchy',
    imageUrl: '/images/6.jpg',
    creator: 'Ralphy',
    price: 1500,
    type: 'Sketch',
    passion: 'ART',
    profession: 'PI'
  },
  {
    id: 7,
    name: 'Blue and Black',
    imageUrl: '/images/7.jpg',
    creator: 'Jason Tod',
    price: 5000,
    type: 'Sketch',
    passion: 'ART',
    profession: 'Tech Geek'
  }
]
 
    export default arts